version: 2.1

# リファレンスパラメータ
defaults: &defaults
  parameters:
    message:
      type: string
      default: hello!

node: &node
  working_directory: ~/repo
  executor:
    name: node/default
    tag: '12.16.0'

# オーブ
orbs:
  node: circleci/node@2.0.1

# ジョブ
jobs:
  hello:
    <<: *defaults
    <<: *node
    steps:
      - run: echo "<< parameters.message >>"
  goodbye:
    <<: *defaults
    <<: *node
    steps:
      - run: echo "goodbye"


# ワークフロー
workflows:
  hello-workflow:
    jobs:
      - start_approve:
          type: approval
      - hello:
          requires: [start_approve]
          message: Hi!
      - goodbye:
          requires: [hello]